### ISSUE TITLE
Segfault in cMojangAPI

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#2232]
I wanted to login into my server, didn't work and then I stopped it to restart. This crash appears.

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4c59700 (LWP 6165)]
0x00007ffff74b4414 in pthread_mutex_lock ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
  Id   Target Id         Frame 
* 4    Thread 0x7ffff4c59700 (LWP 6165) "MCServer" 0x00007ffff74b4414 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
  2    Thread 0x7ffff6b51700 (LWP 6163) "MCServer" 0x00007ffff6c46859 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
  1    Thread 0x7ffff7fc5780 (LWP 6162) "MCServer" 0x00007ffff74b366b in pthread_join () from /lib/x86_64-linux-gnu/libpthread.so.0

Thread 4 (Thread 0x7ffff4c59700 (LWP 6165)):
#0  0x00007ffff74b4414 in pthread_mutex_lock ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00000000005b966a in cCSLock::cCSLock(cCriticalSection&) ()
#2  0x00000000006a0bf8 in cMojangAPI::AddPlayerProfile(std::string const&, std::string const&, Json::Value const&) ()
#3  0x000000000069b012 in cAuthenticator::AuthWithYggdrasil(std::string&, std::string const&, std::string&, Json::Value&) ()
#4  0x000000000069a5c9 in cAuthenticator::Execute() ()
#5  0x00007ffff71e5e40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff74b2182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff6c4c47d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7ffff6b51700 (LWP 6163)):
#0  0x00007ffff6c46859 in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000950148 in epoll_dispatch ()
#2  0x0000000000945724 in event_base_loop ()
#3  0x00007ffff71e5e40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff74b2182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007ffff6c4c47d in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff7fc5780 (LWP 6162)):
#0  0x00007ffff74b366b in pthread_join ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ffff71e5d87 in std::thread::join() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000005ba95e in cIsThread::Wait() ()
#3  0x0000000000578cda in cRoot::Start(std::unique_ptr<cSettingsRepositoryInterface, std::default_delete<cSettingsRepositoryInterface> >) ()
#4  0x00000000005ab00d in universalMain(std::unique_ptr<cSettingsRepositoryInterface, std::default_delete<cSettingsRepositoryInterface> >) ()
#5  0x00000000005ada84 in main ()
```

**Comment by madmaxoft** [comment]
This was most likely caused by something entirely different, and there's no way to trace it back. I'd venture a guess that when you tried logging in, the auth process deadlocked somewhere (so you couldn't log in) and then when you stopped the server, the auth process got unblocked, but the authentificator was already destroyed at that time (hence the crash).

**Comment by Seadragon91** [comment]
Okay, my internet connection is sometimes very bad. I think I was in the queue to be authenticated, but It takes to long, so I stopped the server and it crashes. 
I don't think that there is a deadlock, because I tried that to reproduce and the server wrote into the console that I has been authenticated, but I did already logged out.
