### ISSUE TITLE
Minecraft client crashed - IndexOutOfBounds

### ISSUE THREAD

**Issue by schillermann** [cuberite/cuberite#2555]
Java version: 1.8.0_60
OS: Windows 10
Minecraft version 1.8.8

I often get this error message from the client an kick out:

```
[Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(14988) exceeds writerIndex(8): UnpooledHeapByteBuf(ridx: 2, widx: 8, cap: 8)
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
    at g.a(SourceFile:45) [1.8.8.jar:?]
    at ave.av(SourceFile:881) [1.8.8.jar:?]
    at ave.a(SourceFile:325) [1.8.8.jar:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [1.8.8.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(14988) exceeds writerIndex(8): UnpooledHeapByteBuf(ridx: 2, widx: 8, cap: 8)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:655) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at em.readBytes(SourceFile:669) ~[1.8.8.jar:?]
    at em.c(SourceFile:243) ~[1.8.8.jar:?]
    at bcy.a(SourceFile:1291) ~[1.8.8.jar:?]
    at gg.a(SourceFile:52) ~[1.8.8.jar:?]
    at gg.a(SourceFile:9) ~[1.8.8.jar:?]
    at fh$1.run(SourceFile:13) ~[1.8.8.jar:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
    at g.a(SourceFile:44) ~[1.8.8.jar:?]
    ... 3 more
```

**Comment by mathiascode** [comment]
Haven't seen similar cases in a while.
