### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#2891]
Here the crash info from pull request #2882 (Travis CI). The crash occurred on spawn generation for the nether world.

```
[13:13:13]   D:    | Cuberite has encountered an error and needs to close
[13:13:13] Details | SIGSEGV: Segmentation fault
[13:13:13] Cuberite Travis gcc RELEASE build id: 8471.3
[13:13:13] from commit id: 2666df582ac3135246d4c266da64072eb51f388c built at: Sun Jan 17 13:08:09 UTC 2016
./Cuberite(_Z15PrintStackTracev+0x14)[0x627694]
./Cuberite[0x6149c3]
/lib/x86_64-linux-gnu/libc.so.6(+0x36150)[0x7f1d01759150]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x7f1d0230ce84]
./Cuberite(_ZN7cCSLockC1ER16cCriticalSection+0x1d)[0x6211bd]
./Cuberite(_ZN15cLightingThread10QueueChunkEiiSt10unique_ptrI19cChunkCoordCallbackSt14default_deleteIS1_EE+0x67)[0x5b89f7]
./Cuberite(_ZN21cSpawnPrepareCallback4CallEiib+0x81)[0x5f0841]
./Cuberite(_ZN15cLightingThread10LightChunkERNS_18cLightingChunkStayE+0x5c)[0x5b7fbc]
./Cuberite(_ZN15cLightingThread7ExecuteEv+0x9d)[0x5b85bd]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8da30)[0x7f1d02082a30]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a)[0x7f1d0230ae9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f1d018172ed]
[13:13:13]   D:    | Cuberite has encountered an error and needs to close
[13:13:13] Details | SIGABRT: Server self-terminated due to an internal fault
[13:13:13] Cuberite Travis gcc RELEASE build id: 8471.3
[13:13:13] from commit id: 2666df582ac3135246d4c266da64072eb51f388c built at: Sun Jan 17 13:08:09 UTC 2016
./Cuberite(_Z15PrintStackTracev+0x14)[0x627694]
./Cuberite[0x6149c3]
/lib/x86_64-linux-gnu/libc.so.6(+0x36150)[0x7f1d01759150]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x35)[0x7f1d017590d5]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x17b)[0x7f1d0175c83b]
./Cuberite[0x6149c8]
/lib/x86_64-linux-gnu/libc.so.6(+0x36150)[0x7f1d01759150]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x7f1d0230ce84]
./Cuberite(_ZN7cCSLockC1ER16cCriticalSection+0x1d)[0x6211bd]
./Cuberite(_ZN15cLightingThread10QueueChunkEiiSt10unique_ptrI19cChunkCoordCallbackSt14default_deleteIS1_EE+0x67)[0x5b89f7]
./Cuberite(_ZN21cSpawnPrepareCallback4CallEiib+0x81)[0x5f0841]
./Cuberite(_ZN15cLightingThread10LightChunkERNS_18cLightingChunkStayE+0x5c)[0x5b7fbc]
./Cuberite(_ZN15cLightingThread7ExecuteEv+0x9d)[0x5b85bd]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8da30)[0x7f1d02082a30]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a)[0x7f1d0230ae9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f1d018172ed]
```

**Comment by Seadragon91** [comment]
Was able to reproduce it in a debug build.

```
#0  0x00007f5b5102ecc9 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f5b510320d8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f5b51027b86 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f5b51027c32 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000881fdd in cLightingThread::QueueChunk (this=0x367b950, a_ChunkX=211273046, a_ChunkZ=-4149511, 
    a_CallbackAfter=...) at /home/lukas/cpp/cuberite/src/LightingThread.cpp:154
#5  0x00000000008dee69 in cSpawnPrepare::PreparedChunkCallback (this=0x7fff0c57f428, a_ChunkX=-4, a_ChunkZ=4)
    at /home/lukas/cpp/cuberite/src/SpawnPrepare.cpp:111
#6  0x00000000008df6ec in cSpawnPrepareCallback::Call (this=0x5c3d2a0, a_ChunkX=-4, a_ChunkZ=4, a_IsSuccess=true)
    at /home/lukas/cpp/cuberite/src/SpawnPrepare.cpp:25
#7  0x000000000088259f in cLightingThread::LightChunk (this=0x7f5b4f129ec8, a_Item=...)
    at /home/lukas/cpp/cuberite/src/LightingThread.cpp:246
#8  0x00000000008824a6 in cLightingThread::Execute (this=0x7f5b4f129ec8)
    at /home/lukas/cpp/cuberite/src/LightingThread.cpp:228
#9  0x0000000000930b59 in cIsThread::DoExecute (this=0x7f5b4f129ec8)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:74
#10 0x00000000009320f2 in std::_Mem_fn<void (cIsThread::*)()>::operator()<, void>(cIsThread*) const (
    this=0x5ac4328, __object=0x7f5b4f129ec8)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:601
#11 0x0000000000932052 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x5ac4320)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1731
#12 0x0000000000932005 in std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)>::operator()() (
    this=0x5ac4320) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:1720
#13 0x0000000000931fdc in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (cIsThread::*)()> (cIsThread*)> >::_M_run() (this=0x5ac4308) at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/thread:115
#14 0x00007f5b51684a40 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007f5b518df182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#16 0x00007f5b510f247d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by Seadragon91** [comment]
Just as info a crashed release build under gdb:
https://travis-ci.org/cuberite/cuberite/jobs/239116939#L3056

**Comment by peterbell10** [comment]
I haven't seen any of these crashes since #3924 was merged. Closing as likely fixed.
