### ISSUE TITLE
Segfault on stop

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3474]
Client version:  1.10.2
Commit id:        build on e8fb85be885f6c32fdeb861b12fb8402de66ebe5
Changed the cert check to be optional and added g flag for debug informations. I couldn't use the debug build, because I always got an assertion error that the player is nullptr.

### Actual behavior
Server crashes on stop

### Steps to reproduce the behavior
I tested the mojang authentication, installed a web server and added a php script that returns the profile of the user. For the UUID I generated a md5 string from the username. Spammed then the server with pycraft.

I stopped the server, while the server tried to authenticate users.
```
Thread 3 (Thread 0x7f6725088700 (LWP 11302)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00000000009a4028 in epoll_dispatch ()
#2  0x00000000009990b1 in event_base_loop ()
#3  0x00000000005f5aee in cNetworkSingleton::RunEventLoop(cNetworkSingleton*) ()
#4  0x00007f67256f7cdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f67259c6464 in start_thread (arg=0x7f6725088700) at pthread_create.c:333
#6  0x00007f67251719df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 2 (Thread 0x7f67264ffb80 (LWP 11301)):
#0  0x00007f67259c76bd in pthread_join (threadid=140080871696128, thread_return=0x0) at pthread_join.c:90
#1  0x00007f67256f7f67 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000005f4fee in cIsThread::Wait() ()
#3  0x00000000005b7bf3 in cRoot::Start(std::unique_ptr<cSettingsRepositoryInterface, std::default_delete<cSettingsRepositoryInterface> >) ()
#4  0x00000000005e9047 in UniversalMain(std::unique_ptr<cSettingsRepositoryInterface, std::default_delete<cSettingsRepositoryInterface> >) ()
#5  0x00000000005e6c87 in main ()

Thread 1 (Thread 0x7f671e98e700 (LWP 11304)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007f67250bd40a in __GI_abort () at abort.c:89
#2  0x00000000005e6df1 in NonCtrlHandler(int) ()
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#5  0x00007f67250bd40a in __GI_abort () at abort.c:89
#6  0x00000000005e6df1 in NonCtrlHandler(int) ()
#7  <signal handler called>
#8  __GI___pthread_mutex_lock (mutex=0xb0) at ../nptl/pthread_mutex_lock.c:67
#9  0x00000000005f374a in cCSLock::cCSLock(cCriticalSection&) ()
#10 0x00000000006eab65 in cMojangAPI::AddPlayerProfile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Json::Value const&) ()
#11 0x00000000006e55e2 in cAuthenticator::AuthWithYggdrasil(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Json::Value&) ()
#12 0x00000000006e4aa8 in cAuthenticator::Execute() ()
#13 0x00007f67256f7cdf in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007f67259c6464 in start_thread (arg=0x7f671e98e700) at pthread_create.c:333
#15 0x00007f67251719df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

**Comment by Seadragon91** [comment]
Go this crash again. This time no authentication enabled, only disconnected all bots.
Tried to reproduce it in a debug build, no luck...
```
#0  __GI___writev (iovcnt=1, iov=0x7ffffea2f520, fd=37) at ../sysdeps/unix/sysv/linux/writev.c:26
#1  __GI___writev (fd=37, iov=0x7ffffea2f520, iovcnt=1) at ../sysdeps/unix/sysv/linux/writev.c:24
#2  0x0000000000a3f03d in evbuffer_write_iovec (buffer=0x7ffff8264a50, fd=37, howmuch=-32)
    at /home/lukas/cpp/cuberite/lib/libevent/buffer.c:2458
#3  evbuffer_write_atmost (buffer=0x7ffff8264a50, fd=37, howmuch=<optimized out>)
    at /home/lukas/cpp/cuberite/lib/libevent/buffer.c:2544
#4  0x0000000000a44875 in bufferevent_writecb (fd=37, event=<optimized out>, arg=0x7ffff82647a0)
    at /home/lukas/cpp/cuberite/lib/libevent/bufferevent_sock.c:295
#5  0x0000000000a4bfdf in event_persist_closure (base=0xc3f5e0, ev=0x7ffff8264830)
    at /home/lukas/cpp/cuberite/lib/libevent/event.c:1629
#6  event_process_active_single_queue (base=0xc3f5e0, activeq=0xc3cd30, max_to_process=2147483647, endtime=0x0)
    at /home/lukas/cpp/cuberite/lib/libevent/event.c:1688
#7  0x0000000000a48cec in event_process_active (base=0xc3f5e0) at /home/lukas/cpp/cuberite/lib/libevent/event.c:1789
#8  event_base_loop (base=0xc3f5e0, flags=<optimized out>) at /home/lukas/cpp/cuberite/lib/libevent/event.c:2012
#9  0x0000000000634373 in cNetworkSingleton::RunEventLoop (a_Self=0xc1cec8 <cNetworkSingleton::Get()::Instance>)
    at /home/lukas/cpp/cuberite/src/OSSupport/NetworkSingleton.cpp:166
#10 0x00007fffff53bb2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007fffff446fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#12 0x00007fffff3694cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by Seadragon91** [comment]
A updated from debug build. Was able to find a way to reproduce it.
```
(gdb) bt
#0  __GI___writev (iovcnt=1, iov=0x7ffffea2f340, fd=133) at ../sysdeps/unix/sysv/linux/writev.c:26
#1  __GI___writev (fd=133, iov=0x7ffffea2f340, iovcnt=1) at ../sysdeps/unix/sysv/linux/writev.c:24
#2  0x0000000008df8aeb in evbuffer_write_iovec (buffer=0x7ffff89498a0, fd=133, howmuch=16384)
    at /home/lukas/cpp/cuberite/lib/libevent/buffer.c:2458
#3  0x0000000008df8cb0 in evbuffer_write_atmost (buffer=0x7ffff89498a0, fd=133, howmuch=16384)
    at /home/lukas/cpp/cuberite/lib/libevent/buffer.c:2544
#4  0x0000000008e00af2 in bufferevent_writecb (fd=133, event=4, arg=0x7ffff89495f0)
    at /home/lukas/cpp/cuberite/lib/libevent/bufferevent_sock.c:295
#5  0x0000000008e0584f in event_persist_closure (base=0x918e4e0, ev=0x7ffff8949680)
    at /home/lukas/cpp/cuberite/lib/libevent/event.c:1629
#6  0x0000000008e05b29 in event_process_active_single_queue (base=0x918e4e0, activeq=0x918e280,
    max_to_process=2147483647, endtime=0x0) at /home/lukas/cpp/cuberite/lib/libevent/event.c:1688
#7  0x0000000008e060a0 in event_process_active (base=0x918e4e0)
    at /home/lukas/cpp/cuberite/lib/libevent/event.c:1789
#8  0x0000000008e067b7 in event_base_loop (base=0x918e4e0, flags=4)
    at /home/lukas/cpp/cuberite/lib/libevent/event.c:2012
#9  0x00000000088a9d84 in cNetworkSingleton::RunEventLoop (a_Self=0x916bdc0 <cNetworkSingleton::Get()::Instance>)
    at /home/lukas/cpp/cuberite/src/OSSupport/NetworkSingleton.cpp:166
#10 0x00000000088aaf53 in std::__invoke_impl<void, void (*)(cNetworkSingleton*), cNetworkSingleton*> (
    __f=@0x918df30: 0x88a9d16 <cNetworkSingleton::RunEventLoop(cNetworkSingleton*)>,
    __args#0=@0x918df28: 0x916bdc0 <cNetworkSingleton::Get()::Instance>) at /usr/include/c++/8/bits/invoke.h:60
#11 0x00000000088aa436 in std::__invoke<void (*)(cNetworkSingleton*), cNetworkSingleton*> (
    __fn=@0x918df30: 0x88a9d16 <cNetworkSingleton::RunEventLoop(cNetworkSingleton*)>,
    __args#0=@0x918df28: 0x916bdc0 <cNetworkSingleton::Get()::Instance>) at /usr/include/c++/8/bits/invoke.h:95
#12 0x00000000088acbe7 in std::thread::_Invoker<std::tuple<void (*)(cNetworkSingleton*), cNetworkSingleton*> >::_M_invoke<0ul, 1ul> (this=0x918df28) at /usr/include/c++/8/thread:244
#13 0x00000000088acba2 in std::thread::_Invoker<std::tuple<void (*)(cNetworkSingleton*), cNetworkSingleton*> >::operator() (this=0x918df28) at /usr/include/c++/8/thread:253
#14 0x00000000088acb86 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(cNetworkSingleton*), cNetworkSingleton*> > >::_M_run (this=0x918df20) at /usr/include/c++/8/thread:196
#15 0x00007fffff6cbb2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007fffff446fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#17 0x00007fffff3694cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
