### ISSUE TITLE
Crash in trying to move items into the hopper

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4410]
### Expected behavior
A hopper should be able to collect items.

### Actual behavior
Server crashes.

Stack trace of crash:
```
#0  0x00000000087a5ad2 in cLazyArray<cItem>::size (this=0x50) at /home/lukas/cpp/cuberite/src/LazyArray.h:80
#1  0x00000000087a5904 in cItemGrid::GetNumSlots (this=0x48) at /home/lukas/cpp/cuberite/src/ItemGrid.h:40
#2  0x0000000008c05272 in cHopperEntity::MoveItemsFromGrid (this=0x7fffd42a0e00, a_Entity=...)
    at /home/lukas/cpp/cuberite/src/BlockEntities/HopperEntity.cpp:457
#3  0x0000000008c04765 in cHopperEntity::MoveItemsIn (this=0x7fffd42a0e00, a_Chunk=..., a_CurrentTick=117777)
    at /home/lukas/cpp/cuberite/src/BlockEntities/HopperEntity.cpp:171
#4  0x0000000008c0445f in cHopperEntity::Tick (this=0x7fffd42a0e00, a_Dt=..., a_Chunk=...)
    at /home/lukas/cpp/cuberite/src/BlockEntities/HopperEntity.cpp:72
#5  0x000000000872db22 in cChunk::Tick (this=0x7fffd80bea40, a_Dt=...) at /home/lukas/cpp/cuberite/src/Chunk.cpp:660
#6  0x0000000008753b61 in cChunkMap::Tick (this=0x928d780, a_Dt=...)
    at /home/lukas/cpp/cuberite/src/ChunkMap.cpp:2194
#7  0x0000000008831898 in cWorld::Tick (this=0x7ffffdad0010, a_Dt=..., a_LastTickDurationMSec=...)
    at /home/lukas/cpp/cuberite/src/World.cpp:1034
#8  0x00000000088289b4 in cWorld::cTickThread::Execute (this=0x7ffffe221818)
    at /home/lukas/cpp/cuberite/src/World.cpp:121
#9  0x000000000886589d in cIsThread::DoExecute (this=0x7ffffe221818)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:73
#10 0x000000000886612c in std::__invoke_impl<void, void (cIsThread::*)(), cIsThread*> (
    __f=@0xe7d02a0: (void (cIsThread::*)(cIsThread * const)) 0x886586e <cIsThread::DoExecute()>, 
    __t=@0xe7d0298: 0x7ffffe221818) at /usr/include/c++/8/bits/invoke.h:73
#11 0x0000000008865cd9 in std::__invoke<void (cIsThread::*)(), cIsThread*> (
    __fn=@0xe7d02a0: (void (cIsThread::*)(cIsThread * const)) 0x886586e <cIsThread::DoExecute()>, 
    __args#0=@0xe7d0298: 0x7ffffe221818) at /usr/include/c++/8/bits/invoke.h:95
#12 0x000000000886643d in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::_M_invoke<0ul, 1ul>
    (this=0xe7d0298) at /usr/include/c++/8/thread:244
#13 0x00000000088663f8 in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::operator() (
    this=0xe7d0298) at /usr/include/c++/8/thread:253
#14 0x00000000088663dc in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> > >::_M_run (this=0xe7d0290) at /usr/include/c++/8/thread:196
#15 0x00007fffff6cbb2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007fffff446fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#17 0x00007fffff3694cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Here the world that causes the crash
[world_crash_hopper.zip](https://github.com/cuberite/cuberite/files/3685315/world_crash_hopper.zip)

Use a client to connect to the world and fly to this coords: x: -85, z: -45.
The crash should occur immediately.

Not sure what there is wrong. Maybe the hopper is not fully loaded (lazy array?) and the server already tries to move the item (cactus) into the hopper's item grid.

**Comment by madmaxoft** [comment]
Aaah, you keep testing code that I'm currently rewriting :(

**Comment by Seadragon91** [comment]
Okay sorry. Wanted to work on the problem where the hopper doesn't work correctly with other containers.

**Comment by madmaxoft** [comment]
Not a problem, just a nod to the funny coincidence. Go ahead and fix it, I'll survive :)
