### ISSUE TITLE
Segmentation Fault on RPi4 AlpineLinux

### ISSUE THREAD

**Issue by OverPie** [cuberite/cuberite#4548]
Client version: 1.12.2
Server OS: Alpine Linux v3.11 armv7l
Cuberite Commit id: [09:13:20] from commit id: approx: 8154bde116df2b0ff2fe535ed1bb87d00a009b52 built at: approx: 2020-03-24 21:16:54 +0000

Sorry for my bad english.

### Expected behavior
Server should start succesfully.

### Actual behavior
Server got segmentation fault.

### Steps to reproduce the behavior
- Build cuberite on RPi 4 "Alpine Linux v3.11 armv7l" with CXXFLAGS="-march=native -O3 -pipe"
- Profit!!

### Server log
```
Starting program: /root/cuberite/Release/Server/Cuberite 
[New LWP 8344]
[New LWP 8345]
[09:19:28] --- Started Log ---
[09:19:28] Cuberite local build build id: Unknown
[09:19:28] from commit id: approx: 8154bde116df2b0ff2fe535ed1bb87d00a009b52 built at: approx: 2020-03-24 21:16:54 +0000
[09:19:28] Creating new server instance...
[09:19:28] Reading server config...
[09:19:28] Regenerating settings.ini, all settings will be reset
[09:19:28] Starting server...
[09:19:28] Loading UpgradeBlockTypePalette...
[09:19:28] Loading per-protocol palettes...
[09:19:29] Loaded palettes for protocol versions: 1.13, 1.14.4
[New LWP 8346]
[09:19:29] Compatible clients: 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x
[09:19:29] Compatible protocol versions 47, 107, 108, 109, 110, 210, 315, 316, 335, 338, 340
[09:19:29] WebServer: The server will run in unsecured HTTP mode.
[09:19:29] Put a valid HTTPS certificate in file 'webadmin/httpscert.crt' and its corresponding private key to 'webadmin/httpskey.pem' (without any password) to enable HTTPS support
[09:19:29] Loaded 755 crafting recipes
[09:19:29] Loaded 67 furnace recipes and 66 fuels
[09:19:29] Loaded 88 brewing recipes
[09:19:29] -- Loading Plugins --
[09:19:29] Initialised Core v.16
[09:19:29] Initialized ChatLog v.3
[09:19:29] -- Loaded 2 Plugins --
[New LWP 8347]
[New LWP 8348]
[New LWP 8349]
[New LWP 8350]
[New LWP 8351]
[New LWP 8352]

Thread 8 "Cuberite" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 8350]
0xb6ee7c22 in operator new(unsigned int) () from /usr/lib/libstdc++.so.6
```

**Comment by madmaxoft** [comment]
Your log seems to be from running under gdb, I therefore assume you can work with gdb at least a bit. Could you please follow https://forum.cuberite.org/thread-631.html and provide as much info as possible on the crash? (I don't have a RasPi4, so I cannot reproduce)

**Comment by OverPie** [comment]
@madmaxoft 
The log:
```
     [08:16:23] --- Started Log ---
     [08:16:23] Cuberite local build build id: Unknown
     [08:16:23] from commit id: approx: 8154bde116df2b0ff2fe535ed1bb87d00a009b52 built at: approx: 2020-03-24 21:16:54 +0000
     [08:16:23] Creating new server instance...
     [08:16:23] Reading server config...
Warn [08:16:23] Regenerating settings.ini, all settings will be reset
     [08:16:23] Starting server...
     [08:16:23] Loading UpgradeBlockTypePalette...
     [08:16:23] Loading per-protocol palettes...
     [08:16:23] Loaded palettes for protocol versions: 1.13, 1.14.4
Info [08:16:23] Compatible clients: 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x
Info [08:16:23] Compatible protocol versions 47, 107, 108, 109, 110, 210, 315, 316, 335, 338, 340
Warn [08:16:23] WebServer: The server will run in unsecured HTTP mode.
```
Crash info (extracted by GDB):
```
Currently logging to "crash.txt".
Logs will be appended to the log file.
Output will be logged and displayed.
Starting program: /root/cuberite/Release/Server/Cuberite 
[New LWP 2650]
[New LWP 2651]
[New LWP 2652]
[New LWP 2653]
[New LWP 2654]
[New LWP 2655]
[New LWP 2656]
[New LWP 2657]
[New LWP 2658]

Thread 8 "Cuberite" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 2656]
0xb6ee7c22 in operator new(unsigned int) () from /usr/lib/libstdc++.so.6
  Id   Target Id           Frame 
  1    LWP 2647 "Cuberite" 0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
  2    LWP 2650 "Cuberite" 0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
  3    LWP 2651 "Cuberite" 0xb6fae710 in epoll_pwait ()
   from /lib/ld-musl-armhf.so.1
  4    LWP 2652 "Cuberite" 0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
  5    LWP 2653 "Cuberite" 0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
  6    LWP 2654 "Cuberite" 0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
  7    LWP 2655 "Cuberite" 0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
* 8    LWP 2656 "Cuberite" 0xb6ee7c22 in operator new(unsigned int) ()
   from /usr/lib/libstdc++.so.6
  9    LWP 2657 "Cuberite" 0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
  10   LWP 2658 "Cuberite" 0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1

Thread 10 (LWP 2658):
#0  0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
#1  0xb6fba18e in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 9 (LWP 2657):
#0  0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
#1  0xb6fba18e in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 8 (LWP 2656):
#0  0xb6ee7c22 in operator new(unsigned int) () from /usr/lib/libstdc++.so.6
#1  0x00555a0a in cBlockArea::SetSize(int, int, int, int) ()
#2  0x00558212 in cBlockArea::Create(int, int, int, int) ()
#3  0x00720442 in cChunkDesc::cChunkDesc(cChunkCoords) ()
#4  0x0074d5ce in cStructGenTrees::GenFinish(cChunkDesc&) ()
#5  0x00720c98 in cComposableGenerator::Generate(cChunkDesc&) ()
#6  0x00578bf4 in cChunkGeneratorThread::DoGenerate(cChunkCoords) ()
#7  0x00578dc2 in cChunkGeneratorThread::Execute() ()
#8  0xb6efc868 in ?? () from /usr/lib/libstdc++.so.6
#9  0xb6fba568 in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (LWP 2655):
#0  0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
#1  0xb6fba18e in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (LWP 2654):
#0  0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
#1  0xb6fba18e in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (LWP 2653):
#0  0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
#1  0xb6fba18e in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (LWP 2652):
#0  0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
#1  0xb6fba18e in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (LWP 2651):
#0  0xb6fae710 in epoll_pwait () from /lib/ld-musl-armhf.so.1
#1  0xb6fae736 in epoll_wait () from /lib/ld-musl-armhf.so.1
#2  0x0091b2aa in epoll_dispatch ()
#3  0x00913004 in event_base_loop ()
#4  0x0060686a in cNetworkSingleton::RunEventLoop(cNetworkSingleton*) ()
#5  0xb6efc868 in ?? () from /usr/lib/libstdc++.so.6
#6  0xb6fba568 in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (LWP 2650):
#0  0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
#1  0xb6fba18e in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (LWP 2647):
#0  0xb6fb9e46 in ?? () from /lib/ld-musl-armhf.so.1
#1  0xb6fba18e in ?? () from /lib/ld-musl-armhf.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by Seadragon91** [comment]
I see musl and looking at the log output the server crashed in chunk generator.
Should be same issue like, #4367, 3406

@OverPie The problem is that in musl the thread stack size is to small.

**Comment by OverPie** [comment]
@Seadragon91 thank you! I have rebuilded musl with more stack size and it working.
