### ISSUE TITLE
Server crash when entering the nether

### ISSUE THREAD

**Issue by Xenoxis** [cuberite/cuberite#4582]
Client version: 1.12
Server OS: Ubuntu 16.04
Cuberite Commit id: 6116f899dee33a6d7bd887f7a57ace17df2ab94f

### Expected behavior
Entering in the Nether and spawn at portail in the nether's side

### Actual behavior
Server Crash

### Steps to reproduce the behavior
Going into the nether

### Server log
```
[14:15:25]   D:    | Cuberite has encountered an error and needs to close
[14:15:25] Details | SIGSEGV: Segmentation fault
[14:15:25] Cuberite local build build id: Unknown
[14:15:25] from commit id: approx: 6116f899dee33a6d7bd887f7a57ace17df2ab94f built at: approx: 2020-03-29 21:58:19 +0100
[14:15:25] Kicking player <playername> for "Server shutdown"
./Cuberite(_Z15PrintStackTracev+0x22)[0x82a9c22]
./Cuberite[0x8296e18]
[0xb77b8bb4]
/lib/i386-linux-gnu/libc.so.6(cfree+0x26)[0xb73e8496]
/usr/lib/i386-linux-gnu/libstdc++.so.6(_ZdlPv+0x18)[0xb76428a8]
./Cuberite(_ZN7cEntity11MoveToWorldEP6cWorld7Vector3IdEbb+0xdf)[0x85032ef]
./Cuberite(_ZN20cNetherPortalScanner10OnDisabledEv+0x8c)[0x823a20c]
./Cuberite(_ZN9cChunkMap12DelChunkStayER10cChunkStay+0xac)[0x81e1c0c]
./Cuberite(_ZN10cChunkStay7DisableEv+0x18)[0x81ec168]
./Cuberite(_ZN9cChunkMap12SetChunkDataER13cSetChunkData+0xec)[0x81e1edc]
./Cuberite(_ZN6cWorld12SetChunkDataER13cSetChunkData+0x2c)[0x828366c]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIxSt5ratioILx1ELx1000EEEES4_+0xbd)[0x828a9cd]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0xba)[0x828b11a]
/usr/lib/i386-linux-gnu/libstdc++.so.6(+0xb4a7d)[0xb7671a7d]
/lib/i386-linux-gnu/libpthread.so.0(+0x6295)[0xb7534295]
/lib/i386-linux-gnu/libc.so.6(clone+0x6e)[0xb745e0ae]
[14:15:25]   D:    | Cuberite has encountered an error and needs to close
[14:15:25] Details | SIGABRT: Server self-terminated due to an internal fault
[14:15:25] Cuberite local build build id: Unknown
[14:15:25] from commit id: approx: 6116f899dee33a6d7bd887f7a57ace17df2ab94f built at: approx: 2020-03-29 21:58:19 +0100
./Cuberite(_Z15PrintStackTracev+0x22)[0x82a9c22]
./Cuberite[0x8296e18]
[0xb77b8bb4]
[0xb77b8bd1]
/lib/i386-linux-gnu/libc.so.6(gsignal+0x39)[0xb73a2ea9]
/lib/i386-linux-gnu/libc.so.6(abort+0x157)[0xb73a4407]
./Cuberite[0x8296e1d]
[0xb77b8bb4]
/lib/i386-linux-gnu/libc.so.6(cfree+0x26)[0xb73e8496]
/usr/lib/i386-linux-gnu/libstdc++.so.6(_ZdlPv+0x18)[0xb76428a8]
./Cuberite(_ZN7cEntity11MoveToWorldEP6cWorld7Vector3IdEbb+0xdf)[0x85032ef]
./Cuberite(_ZN20cNetherPortalScanner10OnDisabledEv+0x8c)[0x823a20c]
./Cuberite(_ZN9cChunkMap12DelChunkStayER10cChunkStay+0xac)[0x81e1c0c]
./Cuberite(_ZN10cChunkStay7DisableEv+0x18)[0x81ec168]
./Cuberite(_ZN9cChunkMap12SetChunkDataER13cSetChunkData+0xec)[0x81e1edc]
./Cuberite(_ZN6cWorld12SetChunkDataER13cSetChunkData+0x2c)[0x828366c]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIxSt5ratioILx1ELx1000EEEES4_+0xbd)[0x828a9cd]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0xba)[0x828b11a]
/usr/lib/i386-linux-gnu/libstdc++.so.6(+0xb4a7d)[0xb7671a7d]
/lib/i386-linux-gnu/libpthread.so.0(+0x6295)[0xb7534295]
/lib/i386-linux-gnu/libc.so.6(clone+0x6e)[0xb745e0ae]
Abandon (core dumped)
```

**Comment by Xenoxis** [comment]
I restarted the server twice and entering the nether works, it was isolated crash ?

**Comment by tigerw** [comment]
There is likely some sort of race condition with entity inter-world travel.

**Comment by Seadragon91** [comment]
I have also a crash with `MoveToWorld`, but not using the nether portal:
```
Cuberite.exe!mtx_do_lock(_Mtx_internal_imp_t * mtx, const xtime * target) Line 90	C++
[Inline Frame] Cuberite.exe!std::_Mutex_base::lock() Line 51	C++
[Inline Frame] Cuberite.exe!cCriticalSection::Lock() Line 23	C++
[Inline Frame] Cuberite.exe!cCSLock::Lock() Line 105	C++
[Inline Frame] Cuberite.exe!cCSLock::{ctor}(cCriticalSection &) Line 81	C++
Cuberite.exe!cWorld::AddEntity(std::unique_ptr<cEntity,std::default_delete<cEntity>> a_Entity) Line 3091	C++
[Inline Frame] Cuberite.exe!cEntity::DoMoveToWorld(const cEntity::sWorldChangeInfo &) Line 1573	C++
Cuberite.exe!cMonster::DoMoveToWorld(const cEntity::sWorldChangeInfo & a_WorldChangeInfo) Line 617	C++
[External Code]	
[Inline Frame] Cuberite.exe!std::_Func_class<void,cWorld &>::operator()(cWorld &) Line 976	C++
Cuberite.exe!cWorld::TickQueuedTasks() Line 1227	C++
Cuberite.exe!cWorld::Tick(std::chrono::duration<__int64,std::ratio<1,1000>> a_Dt, std::chrono::duration<__int64,std::ratio<1,1000>> a_LastTickDurationMSec) Line 1048	C++
Cuberite.exe!cWorld::cTickThread::Execute() Line 123	C++
[External Code]	
Cuberite.exe!thread_start<unsigned int (__cdecl*)(void *),1>(void * const parameter) Line 97	C++
[External Code]	
```

**Comment by Xenoxis** [comment]
Ok, now cuberite crash every time i'm going into the nether

(Commit 318d31dc394da9faea11544ad6e485f1b5eabbdb)

`[13:10:44]   D:    | Cuberite has encountered an error and needs to close
[13:10:44] Details | SIGSEGV: Segmentation fault
[13:10:44] Cuberite local build build id: Unknown
[13:10:44] from commit id: approx: 318d31dc394da9faea11544ad6e485f1b5eabbdb built at: approx: 2020-04-02 17:05:07 +0300
./Cuberite(_Z15PrintStackTracev+0x22)[0x82a9a12]
./Cuberite[0x8296bf8]
[0xb77c8bb4]
[13:10:44]   D:    | Cuberite has encountered an error and needs to close
[13:10:44] Details | SIGABRT: Server self-terminated due to an internal fault
[13:10:44] Cuberite local build build id: Unknown
[13:10:44] from commit id: approx: 318d31dc394da9faea11544ad6e485f1b5eabbdb built at: approx: 2020-04-02 17:05:07 +0300
./Cuberite(_Z15PrintStackTracev+0x22)[0x82a9a12]
./Cuberite[0x8296bf8]
[0xb77c8bb4]
[0xb77c8bd1]
/lib/i386-linux-gnu/libc.so.6(gsignal+0x39)[0xb73b2ea9]
/lib/i386-linux-gnu/libc.so.6(abort+0x157)[0xb73b4407]
./Cuberite[0x8296bfd]
[0xb77c8bb4]
Abandon (core dumped)`

**Comment by mathiascode** [comment]
@Seadragon91 What did you do exactly? Looks like a monster was moved.

**Comment by mathiascode** [comment]
@Seadragon91's stacktrace mentions https://github.com/cuberite/cuberite/blob/01b8ed5295875262a91b60af878bf2a18c1b7aae/src/World.cpp#L3091

Is there a reason we're setting the world twice?

https://github.com/cuberite/cuberite/blob/01b8ed5295875262a91b60af878bf2a18c1b7aae/src/World.cpp#L1029
https://github.com/cuberite/cuberite/blob/01b8ed5295875262a91b60af878bf2a18c1b7aae/src/World.cpp#L3091

**Comment by Seadragon91** [comment]
@mathiascode That was a crash I got during fuzzing, but yes a monster was moved. I run the code many times again, but no crash.

**Comment by Seadragon91** [comment]
@Xenoxis Can you use a debug build under gdb?

**Comment by peterbell10** [comment]
Is it possible the entity was destroyed before the nether portal scanner finished?

**Comment by mathiascode** [comment]
At one point the /portal command repeatedly crashed the server for me, but I haven't been able to reproduce it since.

**Comment by Seadragon91** [comment]
@peterbell10 Was able to get a crash for you idea, I added a hook to remove the player when he enters the portal.

**Comment by Seadragon91** [comment]
Was able to crash the server by spawning with the `/portal` command and then closing the connection (stopping pycraft script):
```
#0  0x0000000000a5ca15 in std::__uniq_ptr_impl<cProtocol, std::default_delete<cProtocol> >::_M_ptr (this=0x1f8)
    at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:150
#1  0x0000000000a5c9d5 in std::unique_ptr<cProtocol, std::default_delete<cProtocol> >::get (this=0x1f8)
    at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:343
#2  0x0000000000a561f5 in std::unique_ptr<cProtocol, std::default_delete<cProtocol> >::operator-> (this=0x1f8)
    at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:337
#3  0x0000000000a4c10e in cClientHandle::SendPlayerMoveLook (this=0x0)
    at /home/lukas/cpp/cuberite/src/ClientHandle.cpp:2831
#4  0x0000000000f6ef9d in cPlayer::FreezeInternal (this=0x7fffc0019730, a_Location=..., a_ManuallyFrozen=false)
    at /home/lukas/cpp/cuberite/src/Entities/Player.cpp:2982
#5  0x0000000000f73cba in cPlayer::DoMoveToWorld (this=0x7fffc0019730, a_WorldChangeInfo=...)
    at /home/lukas/cpp/cuberite/src/Entities/Player.cpp:2076
#6  0x0000000000f47a04 in cEntity::MoveToWorld(cWorld*, Vector3<double>, bool, bool)::$_3::operator()(cWorld&) const
    (this=0x7fffe07c7bb8, a_CurWorld=...) at /home/lukas/cpp/cuberite/src/Entities/Entity.cpp:1604
#7  0x0000000000f47852 in std::_Function_handler<void (cWorld&), cEntity::MoveToWorld(cWorld*, Vector3<double>, bool, bool)::$_3>::_M_invoke(std::_Any_data const&, cWorld&) (__functor=..., __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:297
#8  0x0000000000b42a7b in std::function<void (cWorld&)>::operator()(cWorld&) const (this=0x7fffe07c7bb8, __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/std_function.h:687
#9  0x0000000000b36ea2 in cWorld::TickQueuedTasks (this=0x7ffffdad0010)
    at /home/lukas/cpp/cuberite/src/World.cpp:1231
#10 0x0000000000b2b3b7 in cWorld::Tick (this=0x7ffffdad0010, a_Dt=..., a_LastTickDurationMSec=...)
    at /home/lukas/cpp/cuberite/src/World.cpp:1048
#11 0x0000000000b2ac55 in cWorld::cTickThread::Execute (this=0x7ffffe221810)
    at /home/lukas/cpp/cuberite/src/World.cpp:123
#12 0x0000000000b710e2 in cIsThread::DoExecute (this=0x7ffffe221810)
    at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:73
#13 0x0000000000b71ca7 in std::__invoke_impl<void, void (cIsThread::*)(), cIsThread*> (
    __f=@0x6663b50: (void (cIsThread::*)(cIsThread * const)) 0xb710b0 <cIsThread::DoExecute()>,
    __t=@0x6663b48: 0x7ffffe221810) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:73
#14 0x0000000000b71bb2 in std::__invoke<void (cIsThread::*)(), cIsThread*> (
    __fn=@0x6663b50: (void (cIsThread::*)(cIsThread * const)) 0xb710b0 <cIsThread::DoExecute()>,
    __args=@0x6663b48: 0x7ffffe221810) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/invoke.h:95
#15 0x0000000000b71b75 in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::_M_invoke<0ul, 1ul>
    (this=0x6663b48) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:244
#16 0x0000000000b71b25 in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::operator() (
    this=0x6663b48) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:253
#17 0x0000000000b718ee in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> > >::_M_run (this=0x6663b40) at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/thread:196
#18 0x00007fffff53bb2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007fffff446fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#20 0x00007fffff3694cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Maybe same problem like in issue #3976

**Comment by Xenoxis** [comment]
`[09:42:10]   D:    | Cuberite has encountered an error and needs to close
[09:42:10] Details | SIGSEGV: Segmentation fault
[09:42:10] Cuberite local build build id: Unknown
[09:42:10] from commit id: approx: aac592f98598aae327d07b2a1bb155e33c6d51b1 built at: approx: 2020-04-03 22:23:38 +0100
./Cuberite(_Z15PrintStackTracev+0x22)[0x82a7e22]
./Cuberite[0x8295008]
[0xb778cbb4]
[0x11cbdc2a]
./Cuberite(_ZN6cWorld15TickQueuedTasksEv+0x1b6)[0x82858f6]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIxSt5ratioILx1ELx1000EEEES4_+0x329)[0x8288c29]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0xba)[0x828916a]
[0x2b99a]
[09:42:10]   D:    | Cuberite has encountered an error and needs to close
[09:42:10] Details | SIGABRT: Server self-terminated due to an internal fault
[09:42:10] Cuberite local build build id: Unknown
[09:42:10] from commit id: approx: aac592f98598aae327d07b2a1bb155e33c6d51b1 built at: approx: 2020-04-03 22:23:38 +0100
./Cuberite(_Z15PrintStackTracev+0x22)[0x82a7e22]
./Cuberite[0x8295008]
[0xb778cbb4]
[0xb778cbd1]
/lib/i386-linux-gnu/libc.so.6(gsignal+0x39)[0xb7376ea9]
/lib/i386-linux-gnu/libc.so.6(abort+0x157)[0xb7378407]
./Cuberite[0x829500d]
[0xb778cbb4]
[0x11cbdc2a]
./Cuberite(_ZN6cWorld15TickQueuedTasksEv+0x1b6)[0x82858f6]
./Cuberite(_ZN6cWorld4TickENSt6chrono8durationIxSt5ratioILx1ELx1000EEEES4_+0x329)[0x8288c29]
./Cuberite(_ZN6cWorld11cTickThread7ExecuteEv+0xba)[0x828916a]
[0x2b99a]
Abandon (core dumped)`

**Comment by tigerw** [comment]
> Is it possible the entity was destroyed before the nether portal scanner finished?

This does indeed look likely for the issue as originally raised, because cNetherPortalScanner stores a (raw) pointer to the entity to be warped. In the stack trace given we had

```
--> [14:15:25] Kicking player <playername> for "Server shutdown"

./Cuberite(_Z15PrintStackTracev+0x22)[0x82a9c22]
./Cuberite[0x8296e18]
[0xb77b8bb4]
/lib/i386-linux-gnu/libc.so.6(cfree+0x26)[0xb73e8496]
/usr/lib/i386-linux-gnu/libstdc++.so.6(_ZdlPv+0x18)[0xb76428a8]
./Cuberite(_ZN7cEntity11MoveToWorldEP6cWorld7Vector3IdEbb+0xdf)[0x85032ef]
./Cuberite(_ZN20cNetherPortalScanner10OnDisabledEv+0x8c)[0x823a20c]
```

which seems to indicate that pointer may have been invalidated.

**Comment by tigerw** [comment]
There may be a secondary issue involving `ScheduleTask`/`TickQueuedTasks`; code that queues a task onto a tick thread may end up holding another (raw) pointer to the entity via the lambda `this` capture (it looks like [`MoveToWorld`](https://github.com/cuberite/cuberite/blob/master/src/Entities/Entity.cpp#L1603) may do this). I don't know on which thread players are destructed but it could be an issue if the lambda-captured `this` ends up stale.

**Comment by Seadragon91** [comment]
@tigerw Do you need stack traces, debug build? Or a way to reproduce it?

**Comment by tigerw** [comment]
Seadragon was https://github.com/Seadragon91/pyCraft/blob/ddos_commands/run_cmd_portal_world.py this the script you used?

**Comment by Seadragon91** [comment]
@tigerw I added a few hooks for portals in this [branch](https://github.com/Seadragon91/cuberite/tree/portal_hooks)

Use that branch and you will get two crashes: entity and player.
Plugin code:
```
function Initialize(Plugin)
	Plugin:SetName("PortalTesting")
	Plugin:SetVersion(1)
	
	cPluginManager:AddHook(cPluginManager.HOOK_PORTAL_ENTERING, OnPlayerEntering)
		
	return true
end

function OnPlayerEntering(a_Entity, a_Destination)
	if (a_Entity:IsPlayer()) then
		a_Entity:GetClientHandle():Kick("ByeBye")
	else
		a_Entity:Destroy()
	end
end
```

Build a portal go though or just throw eggs / snowballs into it.

**Comment by tigerw** [comment]
Could you test this branch https://github.com/cuberite/cuberite/tree/attachportal to see if it helps?

It aims to fix entities being destroyed while warping issue.

**Comment by Seadragon91** [comment]
Tested and got no crash :)

**Comment by Seadragon91** [comment]
This can be closed, I think.

**Comment by bearbin** [comment]
Closing as fixed by #4623

**Comment by Seadragon91** [comment]
Started working on my branch for portal hooks to implement the changes from master...
When I tested it I got a deadlock... Sorry @tigerw 

```
Thread 9 (Thread 0x7ffff4830700 (LWP 4458)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
#1  0x00007fffff4497d1 in __GI___pthread_mutex_lock (mutex=0xbef7240) at ../nptl/pthread_mutex_lock.c:115
#2  0x00000000088b23e0 in __gthread_mutex_lock (__mutex=0xbef7240) at /usr/include/x86_64-linux-gnu/c++/8/bits/gthr-default.h:748
#3  0x00000000088b2430 in __gthread_recursive_mutex_lock (__mutex=0xbef7240) at /usr/include/x86_64-linux-gnu/c++/8/bits/gthr-default.h:810
#4  0x00000000088b2464 in std::recursive_mutex::lock (this=0xbef7240) at /usr/include/c++/8/mutex:107
#5  0x00000000088b2075 in cCriticalSection::Lock (this=0xbef7230) at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:23
#6  0x00000000088b228e in cCSLock::Lock (this=0x7ffff482f470) at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:105
#7  0x00000000088b21df in cCSLock::cCSLock (this=0x7ffff482f470, a_CS=...) at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:81
#8  0x00000000087a2e10 in cChunkMap::AddChunkStay (this=0xbef7230, a_ChunkStay=...) at /home/lukas/cpp/cuberite/src/ChunkMap.cpp:2247
#9  0x00000000087b1a9d in cChunkStay::Enable (this=0x7ffff052c9a0, a_ChunkMap=...) at /home/lukas/cpp/cuberite/src/ChunkStay.cpp:86
#10 0x000000000881f826 in cNetherPortalScanner::cNetherPortalScanner (this=0x7ffff052c9a0, a_MovingEntity=..., a_DestinationWorld=..., a_DestPosition=..., a_MaxY=128) at /home/lukas/cpp/cuberite/src/NetherPortalScanner.cpp:42
#11 0x0000000008c07c55 in cEntity::DetectPortal (this=0x7ffff014bc90) at /home/lukas/cpp/cuberite/src/Entities/Entity.cpp:1442
#12 0x0000000008c060d3 in cEntity::Tick (this=0x7ffff014bc90, a_Dt=..., a_Chunk=...) at /home/lukas/cpp/cuberite/src/Entities/Entity.cpp:927
#13 0x0000000008c3a109 in cProjectileEntity::Tick (this=0x7ffff014bc90, a_Dt=..., a_Chunk=...) at /home/lukas/cpp/cuberite/src/Entities/ProjectileEntity.cpp:373
#14 0x0000000008c3e54b in cThrownEggEntity::Tick (this=0x7ffff014bc90, a_Dt=..., a_Chunk=...) at /home/lukas/cpp/cuberite/src/Entities/ThrownEggEntity.cpp:67
#15 0x000000000877d730 in cChunk::Tick (this=0x7fffc00252a0, a_Dt=...) at /home/lukas/cpp/cuberite/src/Chunk.cpp:681
#16 0x00000000087a26c3 in cChunkMap::Tick (this=0x91ed530, a_Dt=...) at /home/lukas/cpp/cuberite/src/ChunkMap.cpp:2094
#17 0x00000000088816a2 in cWorld::Tick (this=0x7ffffdad0010, a_Dt=..., a_LastTickDurationMSec=...) at /home/lukas/cpp/cuberite/src/World.cpp:1040
#18 0x00000000088797f0 in cWorld::cTickThread::Execute (this=0x7ffffe2217d8) at /home/lukas/cpp/cuberite/src/World.cpp:123
#19 0x00000000088b4a1d in cIsThread::DoExecute (this=0x7ffffe2217d8) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:73
#20 0x00000000088b52ac in std::__invoke_impl<void, void (cIsThread::*)(), cIsThread*> (__f=@0xe884b40: (void (cIsThread::*)(class cIsThread * const)) 0x88b49ee <cIsThread::DoExecute()>, __t=@0xe884b38: 0x7ffffe2217d8) at /usr/include/c++/8/bits/invoke.h:73
#21 0x00000000088b4e59 in std::__invoke<void (cIsThread::*)(), cIsThread*> (__fn=@0xe884b40: (void (cIsThread::*)(class cIsThread * const)) 0x88b49ee <cIsThread::DoExecute()>, __args#0=@0xe884b38: 0x7ffffe2217d8) at /usr/include/c++/8/bits/invoke.h:95
#22 0x00000000088b55bd in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::_M_invoke<0ul, 1ul> (this=0xe884b38) at /usr/include/c++/8/thread:244
#23 0x00000000088b5578 in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::operator() (this=0xe884b38) at /usr/include/c++/8/thread:253
#24 0x00000000088b555c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> > >::_M_run (this=0xe884b30) at /usr/include/c++/8/thread:196
#25 0x00007fffff6cbb2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#26 0x00007fffff446fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#27 0x00007fffff3694cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


Thread 14 (Thread 0x7fffe5fb0700 (LWP 4467)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
#1  0x00007fffff4497d1 in __GI___pthread_mutex_lock (mutex=0x91ed540) at ../nptl/pthread_mutex_lock.c:115
#2  0x00000000088b23e0 in __gthread_mutex_lock (__mutex=0x91ed540) at /usr/include/x86_64-linux-gnu/c++/8/bits/gthr-default.h:748
#3  0x00000000088b2430 in __gthread_recursive_mutex_lock (__mutex=0x91ed540) at /usr/include/x86_64-linux-gnu/c++/8/bits/gthr-default.h:810
#4  0x00000000088b2464 in std::recursive_mutex::lock (this=0x91ed540) at /usr/include/c++/8/mutex:107
#5  0x00000000088b2075 in cCriticalSection::Lock (this=0x91ed530) at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:23
#6  0x00000000088b228e in cCSLock::Lock (this=0x7fffe5faf920) at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:105
#7  0x00000000088b21df in cCSLock::cCSLock (this=0x7fffe5faf920, a_CS=...) at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:81
#8  0x000000000879ffe3 in cChunkMap::DoWithEntityByID(unsigned int, cFunctionRef<bool (cEntity&)>) (this=0x91ed530, a_UniqueID=87, a_Callback=...) at /home/lukas/cpp/cuberite/src/ChunkMap.cpp:1346
#9  0x0000000008887925 in cWorld::DoWithEntityByID(unsigned int, cFunctionRef<bool (cEntity&)>) (this=0x7ffffdad0010, a_UniqueID=87, a_Callback=...) at /home/lukas/cpp/cuberite/src/World.cpp:2805
#10 0x00000000088204fa in cNetherPortalScanner::OnDisabled (this=0x7ffff0197780) at /home/lukas/cpp/cuberite/src/NetherPortalScanner.cpp:302
#11 0x00000000087a3209 in cChunkMap::DelChunkStay (this=0xbef7230, a_ChunkStay=...) at /home/lukas/cpp/cuberite/src/ChunkMap.cpp:2313
#12 0x00000000087b1b30 in cChunkStay::Disable (this=0x7ffff0197780) at /home/lukas/cpp/cuberite/src/ChunkStay.cpp:99
#13 0x000000000879c2e1 in cChunkMap::SetChunkData (this=0xbef7230, a_SetChunkData=...) at /home/lukas/cpp/cuberite/src/ChunkMap.cpp:314
#14 0x000000000888613d in cWorld::SetChunkData (this=0x7ffffcb60010, a_SetChunkData=...) at /home/lukas/cpp/cuberite/src/World.cpp:2354
#15 0x00000000088812a1 in cWorld::Tick (this=0x7ffffcb60010, a_Dt=..., a_LastTickDurationMSec=...) at /home/lukas/cpp/cuberite/src/World.cpp:991
#16 0x00000000088797f0 in cWorld::cTickThread::Execute (this=0x7ffffd2b17d8) at /home/lukas/cpp/cuberite/src/World.cpp:123
#17 0x00000000088b4a1d in cIsThread::DoExecute (this=0x7ffffd2b17d8) at /home/lukas/cpp/cuberite/src/OSSupport/IsThread.cpp:73
#18 0x00000000088b52ac in std::__invoke_impl<void, void (cIsThread::*)(), cIsThread*> (__f=@0xe884d60: (void (cIsThread::*)(class cIsThread * const)) 0x88b49ee <cIsThread::DoExecute()>, __t=@0xe884d58: 0x7ffffd2b17d8) at /usr/include/c++/8/bits/invoke.h:73
#19 0x00000000088b4e59 in std::__invoke<void (cIsThread::*)(), cIsThread*> (__fn=@0xe884d60: (void (cIsThread::*)(class cIsThread * const)) 0x88b49ee <cIsThread::DoExecute()>, __args#0=@0xe884d58: 0x7ffffd2b17d8) at /usr/include/c++/8/bits/invoke.h:95
#20 0x00000000088b55bd in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::_M_invoke<0ul, 1ul> (this=0xe884d58) at /usr/include/c++/8/thread:244
#21 0x00000000088b5578 in std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> >::operator() (this=0xe884d58) at /usr/include/c++/8/thread:253
#22 0x00000000088b555c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (cIsThread::*)(), cIsThread*> > >::_M_run (this=0xe884d50) at /usr/include/c++/8/thread:196
#23 0x00007fffff6cbb2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#24 0x00007fffff446fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#25 0x00007fffff3694cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by tigerw** [comment]
Hm, could you try #4682?
