### ISSUE TITLE
cChunk::CheckBlocks: double free or corruption

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4721]
Client version: 1.12.2
Server OS: Linux

### Actual behavior
Server segfault:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffff292535 in __GI_abort () at abort.c:79
#2  0x00007fffff2e9508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fffff3f428d "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fffff2efc1a in malloc_printerr (str=str@entry=0x7fffff3f6018 "double free or corruption (!prev)")
    at malloc.c:5341
#4  0x00007fffff2f173c in _int_free (av=0x7fffbc000020, p=0x7fffbc176ee0, have_lock=<optimized out>)
    at malloc.c:4309
#5  0x000000000058b7d9 in cChunk::CheckBlocks() ()
#6  0x000000000058b3c9 in cChunk::Tick(std::chrono::duration<long, std::ratio<1l, 1000l> >) ()
#7  0x00000000005a17fe in cChunkMap::Tick(std::chrono::duration<long, std::ratio<1l, 1000l> >) ()
#8  0x0000000000616c28 in cWorld::Tick(std::chrono::duration<long, std::ratio<1l, 1000l> >, std::chrono::duration<long, std::ratio<1l, 1000l> >) ()
#9  0x00000000006168af in cWorld::cTickThread::Execute() ()
#10 0x00007fffff53bb2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007fffff446fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#12 0x00007fffff3694cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### Steps to reproduce the behavior
Wasn't able to reproduce it. Server was under heavy load and ram usage was about 1,5 GByte.

**Comment by Seadragon91** [comment]
Closing as duplicate of #3572.
