### ISSUE TITLE
[Assertion failed] BlockTrapdoor.h/BlockFaceToMetadata lacks checks for BLOCK_FACE_YM/BLOCK_FACE_YP

### ISSUE THREAD

**Issue by ghost** [cuberite/cuberite#4878]
Client version: 1.10.2
Server OS: linux
Cuberite Commit id: a90dedffeba758fa7b7e625b43a3b400da6e5d31

BlockTrapdoor BlockFaceToMetaData assertion fail

### Steps to reproduce the behavior
1. Put a trapdoor on a horizontal surface, not adjacent to vertical, like this (vanilla):
![2020-09-17_02 34 38](https://user-images.githubusercontent.com/60849082/93399313-da3feb80-f86c-11ea-97a4-8b4c314b780f.png)

### Server log
```
(gdb) run
....
[bf2385dcd3a2e19a|02:33:08] Assertion failed: !"Unhandled block face!", file /home/wf/workdesk/slate/cuberite/src/Blocks/BlockTrapdoor.h, line 113

Thread 9 "Cuberite" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffec09e700 (LWP 45513)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
```

### The code in question
```cpp
	inline static NIBBLETYPE BlockFaceToMetaData(eBlockFace a_BlockFace)
	{
		switch (a_BlockFace)
		{
			case BLOCK_FACE_ZP: return 0x1;
			case BLOCK_FACE_ZM: return 0x0;
			case BLOCK_FACE_XP: return 0x3;
			case BLOCK_FACE_XM: return 0x2;
			case BLOCK_FACE_NONE:			
			case BLOCK_FACE_YM:
			case BLOCK_FACE_YP:
			{
				ASSERT(!"Unhandled block face!");
				return 0;
			}
		}
		UNREACHABLE("Unsupported block face");
	}
```

Also here
```cpp
	inline static eBlockFace BlockMetaDataToBlockFace(NIBBLETYPE a_Meta)
	{
		switch (a_Meta & 0x3)
		{
			case 0x0: return BLOCK_FACE_ZM;
			case 0x1: return BLOCK_FACE_ZP;
			case 0x2: return BLOCK_FACE_XM;
			case 0x3: return BLOCK_FACE_XP;
			default:
			{
				ASSERT(!"Unhandled block meta!");
				return BLOCK_FACE_NONE;
			}
		}
	}
```

**Comment by theophriene** [comment]
Forgot to add:
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6cc0921 in __GI_abort () at abort.c:79
#2  0x00005555557c1b70 in cBlockTrapdoorHandler::GetPlacementBlockTypeMeta(cChunkInterface&, cPlayer&, Vector3<int>, eBlockFace, Vector3<int>, unsigned char&, unsigned char&) ()
#3  0x00005555556e34b6 in cItemHandler::GetPlacementBlockTypeMeta(cWorld*, cPlayer*, Vector3<int>, eBlockFace, Vector3<int>, unsigned char&, unsigned char&) ()
#4  0x00005555556e318b in cItemHandler::GetBlocksToPlace(cWorld&, cPlayer&, cItem const&, Vector3<int>, eBlockFace, Vector3<int>, std::vector<sSetBlock, std::allocator<sSetBlock> >&) ()
#5  0x00005555556e7784 in cItemHandler::OnPlayerPlace(cWorld&, cPlayer&, cItem const&, Vector3<int>, eBlockFace, Vector3<int>) ()
#6  0x0000555555963055 in cClientHandle::HandleRightClick(int, int, int, eBlockFace, int, int, int, eHand) ()
#7  0x000055555565aea7 in cProtocol_1_11_0::HandlePacketBlockPlace(cByteBuffer&) ()
#8  0x000055555565cbde in cProtocol_1_12_1::HandlePacket(cByteBuffer&, unsigned int) ()
#9  0x0000555555683435 in cProtocol_1_8_0::AddReceivedData(cByteBuffer&, char const*, unsigned long) ()
#10 0x000055555566bcba in cProtocol_1_8_0::DataReceived(cByteBuffer&, char const*, unsigned long) ()
#11 0x000055555595923e in cClientHandle::ProcessProtocolInOut() ()
#12 0x0000555555963526 in cClientHandle::Tick(float) ()
#13 0x00005555558d34ff in cWorld::TickClients(float) ()
#14 0x00005555558e1833 in cWorld::Tick(std::chrono::duration<long, std::ratio<1l, 1000l> >, std::chrono::duration<long, std::ratio<1l, 1000l> >) ()
#15 0x00005555558e1e84 in cWorld::cTickThread::Execute() ()
#16 0x00005555556a30ec in cIsThread::DoExecute() ()
#17 0x00007ffff79036df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007ffff70786db in start_thread (arg=0x7fffe77fe700) at pthread_create.c:463
#19 0x00007ffff6da171f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
