### ISSUE TITLE
API: Segfault in destructor of cLuaWindow on shutdown

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#4894]
Client version: 1.12.2
Server OS: Windows/Linux
Cuberite Commit id: (272a8029e0b8280f61ad2d3bfd0e8353d4256aec)

### Expected behavior
Server should not crash on shutdown.

### Actual behavior
Server crashes on shutdown.

### Steps to reproduce the behavior
Create a plugin with this code, run console command `testit` and stop the server:
```lua
function Initialize(Plugin)
	Plugin:SetName("TestCode")
	Plugin:SetVersion(1)

	cPluginManager:BindConsoleCommand("testit",
		function(a_Split)
			cLuaWindow(cWindow.wtDropSpenser, 1, 1, 'JustAString')
			print("called")
			return true
		end, "testit")
	
	return true
end
```

### Stack trace
```
#0  __GI___pthread_mutex_lock (mutex=0x10) at ../nptl/pthread_mutex_lock.c:67
#1  0x000000000096cf43 in __gthread_mutex_lock (__mutex=0x10)
    at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/gthr-default.h:748
#2  0x000000000096cf15 in __gthread_recursive_mutex_lock (__mutex=0x10)
    at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/x86_64-linux-gnu/c++/8/bits/gthr-default.h:810
#3  0x000000000096d028 in std::recursive_mutex::lock (this=0x10)
    at /usr/lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/mutex:107
#4  0x000000000096cbb6 in cCriticalSection::Lock (this=0x0)
    at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:23
#5  0x000000000096cd92 in cCSLock::Lock (this=0x7ffffffecc10)
    at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:105
#6  0x000000000096cd17 in cCSLock::cCSLock (this=0x7ffffffecc10, a_CS=0x0)
    at /home/lukas/cpp/cuberite/src/OSSupport/CriticalSection.cpp:70
#7  0x000000000059c60f in cWorld::cLock::cLock (this=0x7ffffffecc10, a_World=...)
    at /home/lukas/cpp/cuberite/src/World.cpp:94
#8  0x00000000005add98 in cWorld::ForEachPlayer(cFunctionRef<bool (cPlayer&)>) (this=0x7ffffd2b0050, a_Callback=...)
    at /home/lukas/cpp/cuberite/src/World.cpp:2561
#9  0x0000000000560d9d in cRoot::ForEachPlayer(cFunctionRef<bool (cPlayer&)>) (this=0x7ffffffedc60, a_Callback=...)
    at /home/lukas/cpp/cuberite/src/Root.cpp:656
#10 0x00000000006a1473 in cLuaWindow::~cLuaWindow (this=0x3870c50)
    at /home/lukas/cpp/cuberite/src/Bindings/LuaWindow.cpp:57
#11 0x00000000006a16dc in cLuaWindow::~cLuaWindow (this=0x3870c50)
    at /home/lukas/cpp/cuberite/src/Bindings/LuaWindow.cpp:53
#12 0x000000000060b7b1 in tolua_collect_cLuaWindow (tolua_S=0x4bb3130)
    at /home/lukas/cpp/cuberite/src/Bindings/Bindings.cpp:206
#13 0x0000000000bde8f4 in luaD_precall (L=0x4bb3130, func=0x387e700, nresults=0)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:319
#14 0x0000000000bdf089 in luaD_call (L=0x4bb3130, func=0x387e700, nResults=0)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:376
#15 0x0000000000bd909c in lua_call (L=0x4bb3130, nargs=1, nresults=0)
    at /home/lukas/cpp/cuberite/lib/lua/src/lapi.c:782
#16 0x0000000000c2cb8c in class_gc_event (L=0x4bb3130)
    at /home/lukas/cpp/cuberite/lib/tolua++/src/lib/tolua_event.c:452
#17 0x0000000000bde8f4 in luaD_precall (L=0x4bb3130, func=0x387e6b0, nresults=0)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:319
#18 0x0000000000bdf089 in luaD_call (L=0x4bb3130, func=0x387e6b0, nResults=0)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:376
#19 0x0000000000be0af5 in GCTM (L=0x4bb3130) at /home/lukas/cpp/cuberite/lib/lua/src/lgc.c:467
#20 0x0000000000be08f8 in luaC_callGCTM (L=0x4bb3130) at /home/lukas/cpp/cuberite/lib/lua/src/lgc.c:479
#21 0x0000000000bec069 in callallgcTM (L=0x4bb3130, ud=0x0) at /home/lukas/cpp/cuberite/lib/lua/src/lstate.c:195
#22 0x0000000000bde018 in luaD_rawrunprotected (L=0x4bb3130, f=0xbec050 <callallgcTM>, ud=0x0)
    at /home/lukas/cpp/cuberite/lib/lua/src/ldo.c:116
#23 0x0000000000bec033 in lua_close (L=0x4bb3130) at /home/lukas/cpp/cuberite/lib/lua/src/lstate.c:209
#24 0x000000000067989f in cLuaState::Close (this=0x3863388)
    at /home/lukas/cpp/cuberite/src/Bindings/LuaState.cpp:565
#25 0x00000000006f248a in cPluginLua::Close (this=0x3863310)
    at /home/lukas/cpp/cuberite/src/Bindings/PluginLua.cpp:75
#26 0x00000000006f3461 in cPluginLua::Unload (this=0x3863310)
    at /home/lukas/cpp/cuberite/src/Bindings/PluginLua.cpp:191
#27 0x000000000071aff4 in cPluginManager::UnloadPluginsNow (this=0x3850160)
    at /home/lukas/cpp/cuberite/src/Bindings/PluginManager.cpp:1296
#28 0x000000000071ae43 in cPluginManager::~cPluginManager (this=0x3850160)
    at /home/lukas/cpp/cuberite/src/Bindings/PluginManager.cpp:40
#29 0x000000000071b02c in cPluginManager::~cPluginManager (this=0x3850160)
    at /home/lukas/cpp/cuberite/src/Bindings/PluginManager.cpp:39
#30 0x000000000055dbdf in cRoot::Run (this=0x7ffffffedc60, a_OverridesRepo=...)
    at /home/lukas/cpp/cuberite/src/Root.cpp:228
#31 0x00000000005cc0e6 in UniversalMain (argc=1, argv=0x7ffffffee148, RunningAsService=false)
    at /home/lukas/cpp/cuberite/src/main.cpp:258
#32 0x00000000005cbf37 in main (argc=1, argv=0x7ffffffee148) at /home/lukas/cpp/cuberite/src/main.cpp:316
```

**Comment by tigerw** [comment]
Possible #2561 or similar accesses to already destructed objects.

**Comment by Seadragon91** [comment]
Bisected the problem down to that pull request https://github.com/cuberite/cuberite/pull/4771
