### ISSUE TITLE
1.13 and ViaVersion and others are broken

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite#5074]
Client version: 1.13 +
Server OS: any

It's this function. If you comment it out everything works
https://github.com/cuberite/cuberite/blob/1c5af8c00dcef2a58f161c898a0bb83744b6ba68/src/Protocol/Protocol_1_12.cpp#L1338

**Comment by mathiascode** [comment]
In my experience, this happened once the "walk_on_water_one_cm" stat was added to the list of the player's stats (world/stats folder). Touching water quickly should trigger the bug.

This seems to happen because the stat was introduced post Minecraft 1.12.2, and thus isn't included in ViaVersion's mappings. https://github.com/ViaVersion/ViaVersion/blob/9fd4795cb306e485b9a73ac0eca26a5eff9482ec/common/src/main/resources/assets/viaversion/data/mapping-lang-1.12-1.13.json

Stack trace:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$5$1.handle(Protocol1_13To1_12_2.java:214) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395) ~[?:?]
	at us.myles.ViaVersion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:44) ~[?:?]
	at us.myles.ViaVersion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:16) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[1.1.2.jar:1.1.2]
	... 27 more
```
https://github.com/ViaVersion/ViaVersion/blob/6761489ebfdb479f4ff3c004307b0d5c509a0438/common/src/main/java/us/myles/ViaVersion/protocols/protocol1_13to1_12_2/Protocol1_13To1_12_2.java#L214

**Comment by 12xx12** [comment]
The stats seems to be the problem... but why does deleting the player file help as the player.json does not store the stats 🤔

**Comment by mathiascode** [comment]
Previous stats seem to be overwritten if a player file is removed.

**Comment by mathiascode** [comment]
Fixed in unstable ViaVersion builds: https://ci.viaversion.com/job/ViaVersion/

**Comment by tigerw** [comment]
Many thanks @12xx12 and @mathiascode, nice interproject collaboration!
