### ISSUE TITLE
API: Functions crashes server on FreeBSD

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#5216]
Server OS: FreeBSD
Cuberite Commit id: 9b97d63f8f939dbc431cc2dcd9eddf959f86603a

### Actual behavior
On freebsd server crashes if one of this example code is called from release build:
```
1:
cBoundingBox(110, 188, 5, 176, 67, 160)
obj:Intersect(nil)

2:
cLineBlockTracer:FirstSolidHitTrace(cRoot:Get():GetDefaultWorld(), true, 255, 1, 1, 1, 1)

3:
cLineBlockTracer:LineOfSightTrace(cRoot:Get():GetWorld('world'), true, 1, 1, 1, 1, 1, 1)
```
The functions calls above causes  a crash in lua, as the calls are not valid. But the server should not crash after showing the lua stacktrace.
If called from a debug build, the server doesn't crash.

### Steps to reproduce the behavior
Call the code above from a plugin

### Stack trace
```
#0  0x0000000800cb12ea in thr_kill () from /lib/libc.so.7
#1  0x0000000800c26064 in raise () from /lib/libc.so.7
#2  0x0000000800cdaf29 in abort () from /lib/libc.so.7
#3  0x0000000800b2722d in __gxx_personality_v0 () from /lib/libcxxrt.so.1
#4  0x0000000800b41b6e in ?? () from /lib/libgcc_s.so.1
#5  0x0000000800b419bb in _Unwind_RaiseException () from /lib/libgcc_s.so.1
#6  0x0000000800b269d6 in __cxa_throw () from /lib/libcxxrt.so.1
#7  0x00000000008f97ed in luaD_throw(lua_State*, int) ()
#8  0x00000000008f52c3 in luaL_error ()
#9  0x00000000006d82b6 in tolua_cLineBlockTracer_LineOfSightTrace(lua_State*) ()
#10 0x00000000008fa21c in luaD_precall(lua_State*, lua_TValue*, int) ()
#11 0x0000000000925c39 in luaV_execute(lua_State*, int) ()
#12 0x00000000008faa24 in luaD_call(lua_State*, lua_TValue*, int) ()
#13 0x00000000008fadc8 in luaD_pcall(lua_State*, void (*)(lua_State*, void*), void*, long, long) ()
#14 0x00000000008f44c2 in lua_pcall ()
#15 0x000000000072f183 in cLuaState::CallFunction(int) ()
#16 0x000000000071f1f5 in LuaCommandHandler::ExecuteCommand(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, cPlayer*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cCommandOutputCallback*) ()
#17 0x000000000071c411 in cPluginManager::ExecuteConsoleCommand(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, cCommandOutputCallback&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) ()
#18 0x0000000000778c49 in cServer::ExecuteConsoleCommand(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cCommandOutputCallback&) ()
#19 0x00000000007716d5 in cRoot::QueueExecuteConsoleCommand(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cCommandOutputCallback&) ()
#20 0x0000000000776f03 in cRoot::Run(cSettingsRepositoryInterface&) ()
#21 0x00000000007560c8 in main ()
```

 Looks like some problem with exception / error handling,

**Comment by tigerw** [comment]
https://github.com/cuberite/cuberite/issues/5183#issuecomment-819574914 possibly
